### ISSUE TITLE
Image spelling error in Demo3

### ISSUE THREAD

**Issue by jacornej** [eric-keller/npp-linux-02-router#6]
Image set to `exagbp` but needs to be set to `exabgp` for it to be a smooth demo.  

https://github.com/eric-keller/npp-linux-02-router/blob/26c943df17ddc2d99aec1758906e1fd092ae47ec/demo3-exabgp/diamond-mod2.clab.yml#L8

**Comment by keithgee** [comment]
Fixed with commit d1dc1e2c0562e0354b050ed129194a2d2cc4c6ae
